spring.application.name=spring-data-jpa-ex
spring.datasource.url=jdbc:postgresql://localhost:5432/codeeditor
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
openai.api.key=${OPEN_API_KEY}
